
title: We Lead
author: Jeff Hay
email: haiku11000@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Inspired by a desire to learn and drawn to helping people find their place; I'm titling this workshop "We Lead".
  As I've learned, so may you.

# social links
I don't have enought time for twitter!
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
