title: We Lead
author: Jeff Hay
email: haiku11000@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Exploring leadership for the rest of us.  Often volunteers can feel intimidated by "leadership" and feel underqualified   
  Learning through the experience and wisdom of many that have previously taken this adventure our basic premise can be outlined as follows:
  -Leaders are learners
  -Together we're better
  -Our strengths...

# social links
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
